In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("cleaned_air_quality.csv")

df.head()

,city,state,latitude,longitude,datetime,month,day_name,is_weekend,season,time_of_day,...,no2_ugm3,so2_ugm3,o3_ugm3,dust_ugm3,aod,us_aqi,aqi_category,pm25_category_india,festival_period,crop_burning_season
0,agartala,tripura,23.8315,91.2868,2022-08-05 00:00:00,8.0,friday,False,monsoon,night,...,21.8,2.7,32.0,0.0,0.14,289.000000,Very Unhealthy,good,False,False
1,gurugram,haryana,28.4595,77.0266,2022-08-05 00:00:00,8.0,friday,False,monsoon,night,...,47.5,18.1,40.0,20.0,0.66,90.000000,Moderate,satisfactory,False,False
2,kolkata,west bengal,22.5726,88.3639,2022-08-05 00:00:00,8.0,friday,False,monsoon,night,...,21.9,18.2,9.0,0.0,0.13,51.000000,Moderate,good,False,False
3,bengaluru,karnataka,12.9716,77.5946,2022-08-05 00:00:00,8.0,friday,False,monsoon,night,...,8.9,2.5,38.0,0.0,0.05,42.833332,Good,good,False,False
4,shimla,himachal pradesh,31.1048,77.1734,2022-08-05 00:00:00,8.0,friday,False,monsoon,night,...,20.0,0.6,49.0,0.0,0.20,37.666668,Good,good,False,False

In [3]:
df["datetime"] = pd.to_datetime(df["datetime"])

In [4]:
df = df.sort_values(["city", "datetime"])

df.reset_index(drop=True, inplace=True)

In [6]:
df["hour"] = df["datetime"].dt.hour

df["day"] = df["datetime"].dt.day

df["year"] = df["datetime"].dt.year

df[["datetime", "hour", "day", "year"]].head()

             datetime  hour  day  year
0 2022-08-05 00:00:00     0    5  2022
1 2022-08-05 01:00:00     1    5  2022
2 2022-08-05 02:00:00     2    5  2022
3 2022-08-05 03:00:00     3    5  2022
4 2022-08-05 04:00:00     4    5  2022

In [7]:
df["aqi_lag_1"] = (
    df.groupby("city")["us_aqi"]
      .shift(1)
)

In [8]:
df["aqi_lag_3"] = (
    df.groupby("city")["us_aqi"]
      .shift(3)
)

In [9]:
df["aqi_lag_6"] = (
    df.groupby("city")["us_aqi"]
      .shift(6)
)

In [10]:
df["aqi_lag_12"] = (
    df.groupby("city")["us_aqi"]
      .shift(12)
)

In [11]:
df["aqi_lag_24"] = (
    df.groupby("city")["us_aqi"]
      .shift(24)
)

In [12]:
df[
    [
        "city",
        "datetime",
        "us_aqi",
        "aqi_lag_1",
        "aqi_lag_24"
    ]
].head(30)

        city            datetime  us_aqi  aqi_lag_1  aqi_lag_24
0   agartala 2022-08-05 00:00:00   289.0        NaN         NaN
1   agartala 2022-08-05 01:00:00   289.0      289.0         NaN
2   agartala 2022-08-05 02:00:00    54.0      289.0         NaN
3   agartala 2022-08-05 03:00:00    54.0       54.0         NaN
4   agartala 2022-08-05 04:00:00    54.0       54.0         NaN
5   agartala 2022-08-05 05:00:00    54.0       54.0         NaN
6   agartala 2022-08-05 06:00:00    55.0       54.0         NaN
7   agartala 2022-08-05 07:00:00    55.0       55.0         NaN
8   agartala 2022-08-05 08:00:00    55.0       55.0         NaN
9   agartala 2022-08-05 09:00:00    54.0       55.0         NaN
10  agartala 2022-08-05 10:00:00    55.0       54.0         NaN
11  agartala 2022-08-05 11:00:00    55.0       55.0         NaN
12  agartala 2022-08-05 12:00:00    55.0       55.0         NaN
13  agartala 2022-08-05 13:00:00    56.0       55.0         NaN
14  agartala 2022-08-05 14:00:00    56.0       56.0         NaN
15  agartala 2022-08-05 15:00:00    56.0       56.0         NaN
16  agartala 2022-08-05 16:00:00    56.0       56.0         NaN
17  agartala 2022-08-05 17:00:00    56.0       56.0         NaN
18  agartala 2022-08-05 18:00:00    56.0       56.0         NaN
19  agartala 2022-08-05 19:00:00    55.0       56.0         NaN
20  agartala 2022-08-05 20:00:00    55.0       55.0         NaN
21  agartala 2022-08-05 21:00:00    55.0       55.0         NaN
22  agartala 2022-08-05 22:00:00    55.0       55.0         NaN
23  agartala 2022-08-05 23:00:00    55.0       55.0         NaN
24  agartala 2022-08-06 00:00:00    54.0       55.0       289.0
25  agartala 2022-08-06 01:00:00    54.0       54.0       289.0
26  agartala 2022-08-06 02:00:00    54.0       54.0        54.0
27  agartala 2022-08-06 03:00:00    54.0       54.0        54.0
28  agartala 2022-08-06 04:00:00    53.0       54.0        54.0
29  agartala 2022-08-06 05:00:00    53.0       53.0        54.0

In [14]:
df[
    [
        "city",
        "datetime",
        "us_aqi",
        "aqi_lag_1",
        "aqi_lag_3",
        "aqi_lag_6",
        "aqi_lag_12",
        "aqi_lag_24"
    ]
].head(30)

,city,datetime,us_aqi,aqi_lag_1,aqi_lag_3,aqi_lag_6,aqi_lag_12,aqi_lag_24
0,agartala,2022-08-05 00:00:00,289.0,NaN,NaN,NaN,NaN,NaN
1,agartala,2022-08-05 01:00:00,289.0,289.0,NaN,NaN,NaN,NaN
2,agartala,2022-08-05 02:00:00,54.0,289.0,NaN,NaN,NaN,NaN
3,agartala,2022-08-05 03:00:00,54.0,54.0,289.0,NaN,NaN,NaN
4,agartala,2022-08-05 04:00:00,54.0,54.0,289.0,NaN,NaN,NaN
5,agartala,2022-08-05 05:00:00,54.0,54.0,54.0,NaN,NaN,NaN
6,agartala,2022-08-05 06:00:00,55.0,54.0,54.0,289.0,NaN,NaN
7,agartala,2022-08-05 07:00:00,55.0,55.0,54.0,289.0,NaN,NaN
8,agartala,2022-08-05 08:00:00,55.0,55.0,54.0,54.0,NaN,NaN
9,agartala,2022-08-05 09:00:00,54.0,55.0,55.0,54.0,NaN,NaN
10,agartala,2022-08-05 10:00:00,55.0,54.0,55.0,54.0,NaN,NaN
11,agartala,2022-08-05 11:00:00,55.0,55.0,55.0,54.0,NaN,NaN
12,agartala,2022-08-05 12:00:00,55.0,55.0,54.0,55.0,289.0,NaN
13,agartala,2022-08-05 13:00:00,56.0,55.0,55.0,55.0,289.0,NaN
14,agartala,2022-08-05 14:00:00,56.0,56.0,55.0,55.0,54.0,NaN
15,agartala,2022-08-05 15:00:00,56.0,56.0,55.0,54.0,54.0,NaN
16,agartala,2022-08-05 16:00:00,56.0,56.0,56.0,55.0,54.0,NaN
17,agartala,2022-08-05 17:00:00,56.0,56.0,56.0,55.0,54.0,NaN
18,agartala,2022-08-05 18:00:00,56.0,56.0,56.0,55.0,55.0,NaN
19,agartala,2022-08-05 19:00:00,55.0,56.0,56.0,56.0,55.0,NaN
20,agartala,2022-08-05 20:00:00,55.0,55.0,56.0,56.0,55.0,NaN
21,agartala,2022-08-05 21:00:00,55.0,55.0,56.0,56.0,54.0,NaN
22,agartala,2022-08-05 22:00:00,55.0,55.0,55.0,56.0,55.0,NaN
23,agartala,2022-08-05 23:00:00,55.0,55.0,55.0,56.0,55.0,NaN
24,agartala,2022-08-06 00:00:00,54.0,55.0,55.0,56.0,55.0,289.0
25,agartala,2022-08-06 01:00:00,54.0,54.0,55.0,55.0,56.0,289.0
26,agartala,2022-08-06 02:00:00,54.0,54.0,55.0,55.0,56.0,54.0
27,agartala,2022-08-06 03:00:00,54.0,54.0,54.0,55.0,56.0,54.0
28,agartala,2022-08-06 04:00:00,53.0,54.0,54.0,55.0,56.0,54.0
29,agartala,2022-08-06 05:00:00,53.0,53.0,54.0,55.0,56.0,54.0

In [15]:
df["aqi_roll_mean_24"] = (
    df.groupby("city")["us_aqi"]
      .transform(lambda x: x.rolling(window=24).mean())
)

In [16]:
df["aqi_roll_max_24"] = (
    df.groupby("city")["us_aqi"]
      .transform(lambda x: x.rolling(window=24).max())
)

In [17]:
df["aqi_roll_min_24"] = (
    df.groupby("city")["us_aqi"]
      .transform(lambda x: x.rolling(window=24).min())
)

In [18]:
df["aqi_roll_std_24"] = (
    df.groupby("city")["us_aqi"]
      .transform(lambda x: x.rolling(window=24).std())
)

In [19]:
df[
    [
        "city",
        "datetime",
        "us_aqi",
        "aqi_roll_mean_24",
        "aqi_roll_max_24",
        "aqi_roll_min_24",
        "aqi_roll_std_24"
    ]
].head(35)

,city,datetime,us_aqi,aqi_roll_mean_24,aqi_roll_max_24,aqi_roll_min_24,aqi_roll_std_24
0,agartala,2022-08-05 00:00:00,289.0,NaN,NaN,NaN,NaN
1,agartala,2022-08-05 01:00:00,289.0,NaN,NaN,NaN,NaN
2,agartala,2022-08-05 02:00:00,54.0,NaN,NaN,NaN,NaN
3,agartala,2022-08-05 03:00:00,54.0,NaN,NaN,NaN,NaN
4,agartala,2022-08-05 04:00:00,54.0,NaN,NaN,NaN,NaN
5,agartala,2022-08-05 05:00:00,54.0,NaN,NaN,NaN,NaN
6,agartala,2022-08-05 06:00:00,55.0,NaN,NaN,NaN,NaN
7,agartala,2022-08-05 07:00:00,55.0,NaN,NaN,NaN,NaN
8,agartala,2022-08-05 08:00:00,55.0,NaN,NaN,NaN,NaN
9,agartala,2022-08-05 09:00:00,54.0,NaN,NaN,NaN,NaN
10,agartala,2022-08-05 10:00:00,55.0,NaN,NaN,NaN,NaN
11,agartala,2022-08-05 11:00:00,55.0,NaN,NaN,NaN,NaN
12,agartala,2022-08-05 12:00:00,55.0,NaN,NaN,NaN,NaN
13,agartala,2022-08-05 13:00:00,56.0,NaN,NaN,NaN,NaN
14,agartala,2022-08-05 14:00:00,56.0,NaN,NaN,NaN,NaN
15,agartala,2022-08-05 15:00:00,56.0,NaN,NaN,NaN,NaN
16,agartala,2022-08-05 16:00:00,56.0,NaN,NaN,NaN,NaN
17,agartala,2022-08-05 17:00:00,56.0,NaN,NaN,NaN,NaN
18,agartala,2022-08-05 18:00:00,56.0,NaN,NaN,NaN,NaN
19,agartala,2022-08-05 19:00:00,55.0,NaN,NaN,NaN,NaN
20,agartala,2022-08-05 20:00:00,55.0,NaN,NaN,NaN,NaN
21,agartala,2022-08-05 21:00:00,55.0,NaN,NaN,NaN,NaN
22,agartala,2022-08-05 22:00:00,55.0,NaN,NaN,NaN,NaN
23,agartala,2022-08-05 23:00:00,55.0,74.541667,289.0,54.0,66.055957
24,agartala,2022-08-06 00:00:00,54.0,64.750000,289.0,54.0,47.770511
25,agartala,2022-08-06 01:00:00,54.0,54.958333,56.0,54.0,0.750604
26,agartala,2022-08-06 02:00:00,54.0,54.958333,56.0,54.0,0.750604
27,agartala,2022-08-06 03:00:00,54.0,54.958333,56.0,54.0,0.750604
28,agartala,2022-08-06 04:00:00,53.0,54.916667,56.0,53.0,0.829702
29,agartala,2022-08-06 05:00:00,53.0,54.875000,56.0,53.0,0.899879
30,agartala,2022-08-06 06:00:00,52.0,54.750000,56.0,52.0,1.073394
31,agartala,2022-08-06 07:00:00,52.0,54.625000,56.0,52.0,1.209114
32,agartala,2022-08-06 08:00:00,51.0,54.458333,56.0,51.0,1.413573
33,agartala,2022-08-06 09:00:00,51.0,54.333333,56.0,51.0,1.578846
34,agartala,2022-08-06 10:00:00,51.0,54.166667,56.0,51.0,1.711004

In [20]:
df["target_aqi_24h"] = (
    df.groupby("city")["us_aqi"]
      .shift(-24)
)

In [21]:
df[
    [
        "city",
        "datetime",
        "us_aqi",
        "target_aqi_24h"
    ]
].head(30)

        city            datetime  us_aqi  target_aqi_24h
0   agartala 2022-08-05 00:00:00   289.0            54.0
1   agartala 2022-08-05 01:00:00   289.0            54.0
2   agartala 2022-08-05 02:00:00    54.0            54.0
3   agartala 2022-08-05 03:00:00    54.0            54.0
4   agartala 2022-08-05 04:00:00    54.0            53.0
5   agartala 2022-08-05 05:00:00    54.0            53.0
6   agartala 2022-08-05 06:00:00    55.0            52.0
7   agartala 2022-08-05 07:00:00    55.0            52.0
8   agartala 2022-08-05 08:00:00    55.0            51.0
9   agartala 2022-08-05 09:00:00    54.0            51.0
10  agartala 2022-08-05 10:00:00    55.0            51.0
11  agartala 2022-08-05 11:00:00    55.0            51.0
12  agartala 2022-08-05 12:00:00    55.0            51.0
13  agartala 2022-08-05 13:00:00    56.0            51.0
14  agartala 2022-08-05 14:00:00    56.0            50.0
15  agartala 2022-08-05 15:00:00    56.0            50.0
16  agartala 2022-08-05 16:00:00    56.0            50.0
17  agartala 2022-08-05 17:00:00    56.0            50.0
18  agartala 2022-08-05 18:00:00    56.0            50.0
19  agartala 2022-08-05 19:00:00    55.0            51.0
20  agartala 2022-08-05 20:00:00    55.0            51.0
21  agartala 2022-08-05 21:00:00    55.0            51.0
22  agartala 2022-08-05 22:00:00    55.0            51.0
23  agartala 2022-08-05 23:00:00    55.0            50.0
24  agartala 2022-08-06 00:00:00    54.0            50.0
25  agartala 2022-08-06 01:00:00    54.0            50.0
26  agartala 2022-08-06 02:00:00    54.0            50.0
27  agartala 2022-08-06 03:00:00    54.0            49.0
28  agartala 2022-08-06 04:00:00    53.0            49.0
29  agartala 2022-08-06 05:00:00    53.0            49.0

In [22]:
print("Shape before:", df.shape)

df = df.dropna()

print("Shape after:", df.shape)

Shape before: (842160, 44)
Shape after: (840766, 44)

In [23]:
print(df.isnull().sum().sum())

0

In [24]:
print(df.columns.tolist())

['city', 'state', 'latitude', 'longitude', 'datetime', 'month', 'day_name', 'is_weekend', 'season', 'time_of_day', 'humidity_percent', 'dew_point_c', 'wind_gusts_kmh', 'precipitation_mm', 'is_raining', 'heavy_rain', 'pressure_msl_hpa', 'cloud_cover_percent', 'pm2_5_ugm3', 'pm10_ugm3', 'co_ugm3', 'no2_ugm3', 'so2_ugm3', 'o3_ugm3', 'dust_ugm3', 'aod', 'us_aqi', 'aqi_category', 'pm25_category_india', 'festival_period', 'crop_burning_season', 'hour', 'day', 'year', 'aqi_lag_1', 'aqi_lag_3', 'aqi_lag_6', 'aqi_lag_12', 'aqi_lag_24', 'aqi_roll_mean_24', 'aqi_roll_max_24', 'aqi_roll_min_24', 'aqi_roll_std_24', 'target_aqi_24h']

In [25]:
df.to_csv("model_dataset.csv", index=False)